### ISSUE TITLE
Home Page Concept

### ISSUE THREAD

**Issue by akallish** [Tombodil/Trope22#6]
@Tombodil 

I have posted on Google Drive a pdf for you to review of the home page. 

It will have a similar structure, except for the following changes:
• that we will not have left and right arrows, we will have carousel dots
• we will use a hamburger icon (I am calling it "Go") with rollover navigation
• instead of having all seven sections on the page. The top carousel and the bottom contact will be persistent. The middle area will swap out based on what a user selects. 

The b and root level pages will remain the same - except for the top positioning area and navigation, and with the addition of "home" as a choice in the navigation.

Let me know what you think.

Best,
Adam

**Comment by Tombodil** [comment]
Hey I got the files from yesterday downloaded so I can start building up the page and I know what we're doing fromt he meeting.

I am currently taking the built pages and porting over the content directly into squarespace as per the other issues. I will begin the page building for this the 31st, as the 31st - 1st is my next weekend and I want the other page types mostly ready to go.

**Comment by Tombodil** [comment]
Fixes inbound. A few took longer then expected but they are fixed - I've attached two screenshots where relevant. Some additional styling on the home page as well. 


HOME PAGE
• Contact form is aligned with the content in the red rectangle: left and right padding scales with screen.
• Hamburger width adapted from pdf provided, _screenshot attached_
--new arrows, bolder, in style of spec. Entire system is now based on a sort of standardized with: between size of 'go', gap to dropdown, dropdown arrow padding. Looks much cleaner. Every measurement is hardcoded, so this can be adjusted faster going forward.

--_Note: arrows are based off font size, but can be made much larger and flush to the left margin per the pdf if preffered._

![home page menu adjustment](https://user-images.githubusercontent.com/36061390/180589819-0572e5bc-60a3-4894-8a01-5c84067f8dea.png)

LANDING PAGE SORTING
• System alert removed. Literal coding error on my end and forgot to remove a commented out debug command. Fixed. 

PUBLISHED PAGE - Agile
• Arrows adjusted with new unicode symbols
• top link given negative margin, css redefine. _screenshot attached_ -If this is not working for you, I have an alternative formatting system I can use if need be. The current iteration is W3C compatible cross-browser. Possible issue was the span not being declared properly for SqS internal formatting logic. 



![arrows and alignment example](https://user-images.githubusercontent.com/36061390/180589759-ddb7d804-6787-47cb-8255-3c9b083938b4.png)


INTERVIEWS
• Added "/" after Publishing
• Added additional 10px space between soundcloud link and the content for "Design In The Moment 85"

INSPIRATION (LINKS LANDING)
• Content update redeployed. Not sure what happened on this one. Fixed now

**Comment by akallish** [comment]
Hello @Tombodil 

As promised, attached you will find concepts for the other carousels. They are all on white backgrounds and have the same visual structure or uses other design patterns we have created. 

You will need to tap into your graphic design and typography skills to refine these concepts so they are refined pages. 

I redid the diagrams and like them better. I would like them as GIF builder files. Do you know how to do them?

[Here is a link to the written content ](https://docs.google.com/document/d/1HMMKFD-qi341cRV7aP9DyUMzfuCx2fwbU5nmvUSoYQg/edit)

[Activating_Carousels.pdf](https://github.com/Tombodil/Trope22/files/9174586/Activating_Carousels.pdf)
[Experience_Carousels.pdf](https://github.com/Tombodil/Trope22/files/9174587/Experience_Carousels.pdf)
[Inspirating_Carousels.pdf](https://github.com/Tombodil/Trope22/files/9174588/Inspirating_Carousels.pdf)
[Solving_Carousels.pdf](https://github.com/Tombodil/Trope22/files/9174589/Solving_Carousels.pdf)

**Comment by Tombodil** [comment]
Hey got these concepts,

Looks very clean, I'll adapt these into html and adjust them to our live
environment, then adjust based on our fonts styling.

I'll be building these and wiring up the new pages Sunday, Monday and
Tuesday. Im stuck out of town until very late, tonight.

I'll have updates on both Monday night and Tuesday night so we're aligned
in what's built as well as feedback.

The home pages will be built up by Monday night and then I'll be building
up the case stories / interview pages on Tuesday. Through these days we can
finalize feedback and fixes. (And I'll wire up all the links. )

TO NOTE ON THE BACKGROUNDS:

I have no idea what gifbuilder / a gifbuilder is other then what a Google
search taught me five mins ago.

Some sort of Adobe based gif editor?

I will need the gif files. I have never done 2d animation work in any
capacity. My skills top off at basic css/jquery transitions.

**Comment by akallish** [comment]
@Tombodil thanks for the reply.

I can build animated GIFs and export out and upload

**Comment by Tombodil** [comment]
@akallish 

_Holy wow Squarespace has some funky margin styling for certain types of content blocks. While it caused some complication, I still like the platform._ 

### I have built the home page carousel blocks. There are two (and a half) outstanding issues before they are ready for review but these will be handled tomorrow. 

1.  I need to give things a formatting pass, with some media query adjustments. The current setup is built with overall correct formatting. However I need the evening (it's 10pm here) to let my brain cool off. 
2. DIAGRAMS A: I will need the gif files for the triangle and process diagrams resampled at twice their prior size. If you look at them on the page, they are upscaled roughly into their layout size: artifacting and blurring is occurring because the source files resolution is too low. 
3. DIAGRAMS B: The triangle gif seems to be missing the beginning step. When it plays it is hidden, then pops into view halfway complete. I've confirmed this on both the source file and in the live environment. 

The above said, that was a lot of building I got done today, and converted into the Squarespace live environment. 

Formatting and fixes will follow tomorrow. I'll be getting to them by about 11 and I'll keep on trucking through tomorrow night. As soon as formatting changes are complete, I'll be building the secondary level navigation and tertiary pages. These are copy/pasting and will go MUCH faster then what I was building today. 

I will update the gif diagrams as soon as I get the revised files.  I will also be making updates once the carousels are ready for a formatting review, so you can give feedback. (currently it's a bit sketchy for detailed feedback)


PS: I gave the bottom social media icons better formatting with media query scaling.  This was the last outstanding part from a prior closed issue. I wanted to note that I fixed it.

**Comment by akallish** [comment]
07-26 Comments

Hello @Tombodil . I reviewed the first iteration of the different site section carousels and have the following comments :

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Default Home Page

• looks good
• the carousel should auto run if nobody interacts with it. Maybe every five seconds
• every carousel statement should have a different background color like the current website

Hamburger
• Activation should be Activating
• It gets stuck and after you make a choice it stays open, and it should go away

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Default Experience

• the title is too close to the text below it
• The first paragraph should be in a larger point size
• the carousel circles should be in gray and black with no key line
• The titles next to the numbers should be in bold and the leading should be tightened and be within the x height of the numbers

Adam
• Experience : Adam Kallish (put space before : and make name light
• Practice Areas should be moved down to align with the top of the paragraph on the left
• chevron buttons should be in bold

Elizabeth
• Experience : Elizabeth Nelson (put space before : and make name light
• chevron buttons should be in bold

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Default Activating

• the title is too close to the text below it
• The first paragraph should be in a larger point size

Activating based on informed exploration
• the title is too close to the text below it
• The first paragraph should be in a larger point size

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Default Solving

• the title should be Solving and is too close to the text below it
• We should add a chevron below File Restore to say "more solutions"

Solving through capabilities
• this really needs typographic sensitivity 
• the first paragraph should be in a larger point size
• the four titles should be much smaller (25%)
• the subtitle should be a little smaller
• the body text the leading is too much - tighten
• the chevron should be centered, larger and the text should be in bold

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Default Inspiring

• The first paragraph should be in a larger point size
• The four areas should have roll over states and they should link to each sub level

**Comment by akallish** [comment]
@Tombodil Hey!

Can you change the Trope Collaborative tagline at the top to read "A human-centered design consultancy that collaborates with clients & users to be more focused, adaptive & competitive."

Thanks

**Comment by Tombodil** [comment]
_Ok, had to custom code some stuff, made some big adjustments. 
There are still some rough edges that I will sort tomorrow. I need to get ready for work in the morning._ 

### CHANGES

HEADER
• Changed the Trope Collaborative tagline to "A human-centered design consultancy that collaborates with clients & users to be more focused, adaptive & competitive."

DEFAULT HOME PAGE
• Carousel now has autorun function based on 8 secs (5 was too fast)! This is interrupted if the user clicks any controls from the dropdown menu, or the manual control dots.
• every carousel statement is a different background color like the prior website
• the carousel circles are in gray and black, key line removed. 
• all chevrons have been given some vertical centering, are now in bold across all slides

HAMBURGER
• 'Activation' changed to 'Activating'
• after choice, there is a 500ms delay, then the dropdown rolls back up. Active state on 'Go' is toggled during this event.

DEFAULT EXPERIENCE
• The first paragraph is a larger point size
• All paragraph elements given additional 10pts default top padding
• Number X height adjusted. Font size and line height adjusted. Media Query based adjustment scales the size down for smaller screens under 1300px
• 'Iterartive' changed to 'Iterative'

ADAM
• Practice Areas formatting bug fixed.
• "Experience : Adam Kallish" fixed name is now NotoLight 
• Chevron buttons are now in bold

ELIZABETH
• "Experience : Elizabeth Nelson" fixed name is now NotoLight 
• Chevron buttons are now in bold
• 'his career' changed to 'her career'

GENERAL ACTIVATING
• New Diagrams added into the site, given html adjustments. The diagrams will work great: but at this size, is there a way to export as 'extra large' and then crop? There is formatting logic added so that I can adjust for any diagram dimensions.

DEFAULT ACTIVATING
• The first paragraph is a larger point size
• All paragraph elements given additional 10pts default top padding

ACTIVATING BASED ON INFORMED EXPLORATION
• The first paragraph is a larger point size
• All paragraph elements given additional 10pts default top padding

DEFAULT SOLVING
• All paragraph elements given additional 10pts default top padding
• Title fixed to correct 'Solving'
• Added a chevron below File Restore, "More Solutions"

SOLVING THROUGH CAPABILITIES
• The first paragraph is a larger point size
• the four titles are much smaller by about 50% difference
• the subtitle is 15% smaller
• the body text is actually slightly larger now. 
• All leading in those cells adjusted

DEFAULT INSPIRING
• The first paragraph is a larger point size
• The four have roll over states, we may need some flavor text for the default state.
---These will get adjustments tomorrow.

**Comment by akallish** [comment]
@Tombodil I will crop the gifs and upload them

**Comment by akallish** [comment]
Hello @Tombodil . I reviewed the latest iteration of the different site sections and we are making progress. I have the following comments :

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Default Home Page

Hamburger
• It still gets stuck and after you make a choice it stays open, and it should go away

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Default Experience

• the title is too close to the text below it
• The first paragraph leading is too much. Reduce
• The titles next to the numbers should be in bold 
• All the number areas should move to the right to give breathing space to the first left paragraph

Adam
• Practice Areas should not have a space between title and the specific areas

Elizabeth
• Practice Areas should not have a space between title and the specific areas

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Default Activating

Activating based on informed exploration
• triangle diagram should be larger to fill space
• process diagram should be larger to fill space

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Default Solving

• the title should be Solving is too close to the text below it

Solving through capabilities
• getting better typographically!
• the four titles should be smaller (25%)
• Full bio link is the wrong title
• the space between columns should be more

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Default Inspiring

• Missing two areas
• The roll-over states are working well

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Solving/Aurora UDAT

• The chevrons should be bolder
• The images should use dots if possible and not left and right arrows

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Publishing/Interviews

• Design Feast logo is squished
• Can we make the other thumbnails slightly larger?

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Interest Areas

• Add space between titles and the descriptive paragraph
• "Back" should be larger and have a chevron (match all other examples)

**Comment by akallish** [comment]
07-28 Comments

Hello @Tombodil . I reviewed the latest iteration of the different site sections and we are making progress. I have the following comments :

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Default Home Page

Carousel Dots
• Increase the contrast between the black and dark gray as they almost look the same

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Default Experience

• the title is too close to the text below it
• The first paragraph leading is too much. Reduce

Carousel Dots
• Increase the contrast between the black and dark gray as they almost look the same

Adam
• Needs a period after workforce transformation.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Default Activating

Carousel Dots
• Increase the contrast between the black and dark gray as they almost look the same

Activating based on informed exploration
• triangle diagram should be larger to fill space

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Default Solving

• the title should be Solving is too close to the text below it

Solving through capabilities
• the four titles should be much smaller (40%)
• Full bio link is wrong title. Should Say "Go to Solutions"
• the space between columns should is now too much

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Default Inspiring

• Missing two areas
• The roll over states are working well

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Solving/Aurora UDAT

• The chevrons should be bolder
• The images should use dots if possible and not left and right arrows

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Publishing/Interviews

• Design Feast logo is squished
• Can we make the other thumbnails slightly larger?

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Interest Areas

• Add space between titles and the descriptive paragraph
• "Back" should be larger and have a chevron (match all other examples)

**Comment by Tombodil** [comment]
### CHANGES INBOUND
_Also some smaller fixes, and I suspect you may have a cache issue as some of the html changes seem to lag behind a day or two for you. I have attached screenshots were applicable._

-------------------------------------------------------------------------

Carousel Dots
• Increased contrast between the black and grey (#ccc)
-- These are global colors. #CCC is most visible across the range of backgrounds. 

HAMBURGER
• Isn't stuck for me- can confirm logic in place and functioning. 

DEFAULT EXPERIENCE
• The titles next to the numbers are now in NotoBlack for better weight.
• All 'larger text' first paragraph leading reduced by CSS to 1.2em.
• Fixed copy typos. 

ADAM
• Practice Areas does not have a space between title and the specific areas
• Added a period after 'workforce transformation' on last paragraph.

ELIZABETH
• Practice Areas does not have a space between title and the specific areas

DEFAULT ACTIVATING

ACTIVATING BASED ON INFORMED EXPLORATION
• triangle height is 500px and adjusted to fill the space more. 

DEFAULT SOLVING -- Screenshot attached!
![solving_and_paragraph_spacing](https://user-images.githubusercontent.com/36061390/181678694-dcf1d31c-9fbf-4680-8daf-e2c784704a2c.png)

• The title is Solving <-- This has got to be a cache error. 
• Solving and all other 'header->text' margins have been given a 20pt increase.


SOLVING THROUGH CAPABILITIES -- Screenshot attached!
![Solving_sizes_and_margins_50pt_gutter](https://user-images.githubusercontent.com/36061390/181678713-92a4d84e-356a-460e-824c-27d4d5f6f303.png)

• Full bio link is fixed.  "Go to Solutions"
• The four titles are reduced by just under half (40%+ reduction). 
• set to 50pts in line with the other slides: This can be manually adjusted

DEFAULT INSPIRING -- Screenshot attached!
![inspiring default](https://user-images.githubusercontent.com/36061390/181678754-120d3249-0511-4947-9bf8-e20d45f3a4a7.png)
![interest_content](https://user-images.githubusercontent.com/36061390/181678847-bd47da95-2a96-4fe7-b558-7a89814fdb22.png)

• Four areas built, and looking at the content, there are four areas. Content looks correct (I may be brainfarting hard on this one). 


SOLVING/AURORA UDAT
• All Chevrons adjusted in size to show bold face better
• Images are now on dots, which is a built in option. Styling and behavior were adjusted, which was a bit funky to figure out. Any backend is going to want to obfuscate config variables, but I got em isolated and styled. Further changes to style will be simple


PUBLISHING/INTERVIEWS -- Screenshot attached!
![interviews_nav_and_tile_formatting](https://user-images.githubusercontent.com/36061390/181678786-54aa09e6-4a45-4e14-9f98-326ec9210866.png)

• Design Feast logo is fixed, possible cache error. I may need higher res imgs. 
• thumbnails increased in size by 30%


INTEREST AREAS
• Added space between titles and the descriptive paragraph (20px, like other padding)
• "Back" changed to use same code as other navigation.

**Comment by akallish** [comment]
07-29 Comments

Hello @Tombodil . I reviewed the latest iteration of the different site sections and we are making progress. I have the following comments :

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Default Home Page

Carousel Dots
• The dot contrasts are improved

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Default Experience

• the title is too close to the text below it
• Reduce white space between 01/02 and 03/04

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Default Activating

Activating based on informed exploration
• triangle diagram is better size wise, but the left side of the triangle is cut off

Activating by connecting design thinking with agile
• diagram is too small. Increase to full width

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Default Solving

• the title should be Solving is too close to the text below it

Solving through capabilities
• reduce paragraph spacing to make content fit better
• I may need to edit the content down to make it fit (let me know)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Default Inspiring

• Still missing two areas

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Solving/Aurora UDAT

• The chevrons should be bolder
• The images should use dots if possible and not left and right arrows

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Publishing/Interviews

• Design Feast logo is squished
• Can we make the other thumbnails slightly larger?

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Interest Areas

• Add space between titles and the descriptive paragraph
• "Back" chevron should be heavier (match all other examples)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Aurora Case Study

• carousel dots should be in the black area with the default dot being white

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Publishing

• Design Feast is still squished

**Comment by akallish** [comment]
Hey @Tombodil :

I took a look at the SquareSpace draft site in full screen mode. Many of my requested changes have not been made.

I have the following additional comments :

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Home Page

• the ratio of the browser to what is seen is off. Can we :
• reduce the white space above the Trope Collaborative by 70%
• reduce the white space between the second line of the tag line and the top of the color rectangle by 40%
• reduce the  height of the rectangle by 10%

When a user scrolls down, I would like the Banner to follow along with the hamburger - or maybe just the hamburger scrolls down

• can you do color roll over states for the social media icons?

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Inspiring


• the four areas have too much white space and feel they are floating away from one another. Can you make the squares larger?

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Publishing

• Design and the creation of Value should be Design and the Creation of Value
• The quotes do not change. We had several quotes that would change.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Interviews

 Interview on Design Methods
• put space between for interview link

**Comment by Tombodil** [comment]
### Friday Changes
_Preamble: Dad needed some help with some stuff when I got home so was crunched on time. Early day tomorrow so have to leave it here to get rest. Everything is noted on completion, mostly everything has been worked through. Please clear cache and check fix status as you're checking the below list_


Default Activating
• diagram is too small, this will need something clever, as a 100% width will keep scaling up or down. I'll be working these over tomorrow, as well as the dropdown changes. Time was a bit tight tonight

CHEVRONS
• Do you have a chevron icon to use? I'm styling font and currently the chevrons are maxed on font weight. I will convert these over to an icon. 

Quotes Feature
• The quotes change on page load. To see this, right click on the page area and select 'reload frame' on chrome based browsers. I'm hoping apple browsers have a similar functionality. 
• I have tested and confirmed that the quotes from the original site are present. 


FORM
• We can do rollovers for the social media icons if you want. Do you want to do the icons but replace the white with the blue we're using? Hover makes it blue, otherwise white?

--I can colorize copies myself, unless you have icons or something else in mind. 

Home
![solving_and_paragraph_spacing](https://user-images.githubusercontent.com/36061390/181872084-20866e2f-1452-466d-9836-a3f7547b2542.png)

• visual space from header to title is same as default slides, but seems larger because there's no colored rectangle. It would be weird to have different margins for color or white slides. Do we want to give the white panels a light grey, or give the overall rectangle area a background? May be a non-issue since this is past user input, but still want to ask. 

• reduced the white space above the Trope Collaborative by 70%
• reduces the white space between the second line of the tag line and the top of the color rectangle.

DEFAULT EXPERIENCE
• All titles bottom margin increased to 30px margin.
• Reduced white space between 01/02 and 03/04

ADAM

ELIZABETH

DEFAULT ACTIVATING

ACTIVATING BASED ON INFORMED EXPLORATION
• triangle diagram has been given left side padding to keep from being cropped.


DEFAULT SOLVING 
• All titles bottom margin increased to 30px margin. 

SOLVING THROUGH CAPABILITIES 
• reduced paragraph spacing: If you have time to edit these down by a sentence, that would be appreciated. Mostly 'Applied Strategy' and 'Experience Design'. 

DEFAULT INSPIRING 
• Squares cannot be larger as the padding from the title now takes up more room of the content rectangle. Rectangle height is based on suqarespace block system, and is hardcoded to 700px. Spacing between squares has been reduced. 

DEFAULT Publishing/Interviews
• 'Design and the creation of Value' is now 'Design and the Creation of Value'. Fixed typo.

SOLVING/AURORA UDAT
• The chevrons should be bolder
• carousel dots are being tested in a nested group, aligned with the slide caption. Active is white. Other slides are grey. Placed in the black area. 

PUBLISHING/INTERVIEWS 
• Design Feast has been given hard coded sizing. 
• Icons have been increased in size to 130px width. This can probably be increased to 170px without much issue. 
• 'interview link' has been given a line space where applicable

INTEREST AREAS
• Space between titles and the descriptive paragraph increased to an additional 20px padding.

**Comment by akallish** [comment]
Hey @Tombodil :

I took a look at the Squarespace draft site in full-screen mode. Many of my requested changes have not been made.

I have the following additional comments :

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Home Page

• color rollover states blue for the social media icons

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Experience Page

• in Adam and Liz pages the image of us has a light gray box background. Can you delete?
• delete Liz' vcf card option

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Activating Page

Activating based on informed exploration
• second paragraph weird rag. Can we move organizational to the first line?
• make triangle larger
• process diagram is still small

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Publishing

• Design Feast logo still squished (see attachment)
![Publishing](https://user-images.githubusercontent.com/35602533/181919127-2284ebf1-1fcf-4d30-b12e-286a1cfa01bb.jpg)



- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Interviews

 Interview on Design Methods
• put space between for interview link 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Chevrons for sub level pages

• match the weight in the chevrons in Adam's bio page but to scale with larger type

**Comment by Tombodil** [comment]
### SAT FIXES: The Late Patch Notes with a very tired Tom
_I may need to rest sun night as I'll be spending all day Mon / Tue on finishing the site building and finishing up any further fixes. Early evening was eaten up trying to trace the Squarespace incompatibility with sticky navigation not displaying over footers._

THE COMPLICATED STUFF: the one thing I can't fix due to a platform issue. 
-----------------------------------------

HOME NAVIGATION - Not fully possible within squarespace. Z-index options limited.
• Make the top navigation sticky: This only has partial support within the Squarespace environment. The main page structure and the footer exist on totally different iFrames. This means that the content or navigation will NEVER display over the footer. It's literally impossible within squarespace. So we'll need to look over whether this works (it works until you scroll to the botom form) or whether to change the navigation back to a set position at the top of the page. 


SIMPLER FIXES
-----------------------------------------

CHEVRONS - FIXED
I almost remade these then figured out what was up at 12:45am. There was a font formatting coming from the parent divs a few levels up. 100% edge case oversite. wow. FIXED!

Experience Page
![bio_pic_example](https://user-images.githubusercontent.com/36061390/182013885-be788d50-7c2c-4022-9240-e2546ce27bdf.png)

• in Adam and Liz pages the image of us has a light gray box background: I couldn't replicate this, so I changed the div border and background to a default white... which should functionally remove it. If you see it in the morning, can you screenshot it?
• deleted Liz' vcf card option

Form Icons
• color rollover states blue for the social media icons. Implemented through CSS. Had to remake the html markup but this works simpler. Sizing functionality at smaller screens has been kept.

Design Feast Icon 
• Wix reformatted the img when we uploaded it. Years later I grabbed this busted version and had no idea what you meant by squished. I finally thought to google search the img (as it's not on their main page) and found a high rez archive img. FIXED.

Activating
• Triangle is larger over 1500px and smaller under 1500px - this should better format for screen sizes. I can add or adjust these formatting rules. 
• process diagram is much larger and screen scales like the triangle diagram. This can be adjusted and fine tuned. 
• second paragraph weird rag: This is based on screen width and auto formatting. If we hard code anything, it will work for a small section of users and break the paragraph for everyone else. This is best left as is.

Interview on Design Methods -- Screenshot attached
![Design_Methods_interview_link_line_break](https://user-images.githubusercontent.com/36061390/182013728-666b5155-b338-4627-9d7d-31181beb0187.png)

• "put space between for interview link" - Do you mean make sure the interview link has a break space above it? I have it set as so. Apologies over the semantic confusion here.

**Comment by akallish** [comment]
Hey @Tombodil :

I took a look at the SquareSpace draft site in full screen mode. I believe we may be on the nome stretch. 

I have the following additional comments :

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Home Page

• to go hamburger is not aligned with Trope Collaborative
• I do not mind that the navigation ends at the contact page
• When you press on "GO" and get the drop downs, they stay persistent until you choose something. If you mouse out of the area, it still is there. Is there a way to mouse out of the selections if you do not choose one?

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Experience Page

• in Adam and Liz pages the image of us has a light gray box background. Still see it!
• Liz link to LinkedIn = https://www.linkedin.com/in/elizabeth-nelson-67325a5/

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Activating Page

Activating by connecting design thinking with agile
• process diagram is still small and centered. I would like it to go the full width of the three columns

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Chevrons for sub level pages

• new chevrons look great!

**Comment by Tombodil** [comment]
### SUNDAY FIXES AND UPDATE

_I am now building the page variations and adding the headers across the site. I will be building these tonight and tomorrow, with the pages going live throughout tomorrow afternoon. I will update you tomorrow night._ 

Activating by connecting design thinking with agile
• The diagram can't full 100% width because there's a max width on the img itself. I've given it three tiers of self adjustment based on screen sizes. 2200px+, 1500px+ and under 1500px

Home Page
• testing a new alignment with trope header
• There is now an auto-close logic with the dropdown menu. it has a safety radius around the menu, giving users infinite time to choose an option. If they mouse away from the dropdown area (or the go button) the menu resets after half a second. This area is an invisible rectangle.

Experience Page - Screenshot attached
![grey_rect_fix_attempt](https://user-images.githubusercontent.com/36061390/182257934-54a6e384-acba-442d-a0eb-5ad627ce7e51.png)
• Can you screencap the grey background you're seeing? If I can see if, then I can better trace back what may be causing it.
• --in Adam and Liz pages the image has a light gray box background. I have attempted to hard code force the background and border area of the img. I have attached a screenshot of this in the live preview, with the browser dev tools showing the debug output of the element. 

• Liz bio: new text adapted to slide structure. link added.

**Comment by akallish** [comment]
Thanks @Tombodil for the updates. The process diagram worries me as it is too small. We need a workaround.

**Comment by Tombodil** [comment]
### WED NIGHT UPDATES - PRE PAGE POPULATION
_Lots of little adjustments and fixes. Removed anomalous behavior. Unified margins, headers and menus across the site._ 

-----------------------------------------------------------------------------------------

SQUARESPACE EDITOR DEBACLE: FIXED
-- Squarespace almost broke the site and I fixed it. We reviewed this Tue night.

SITE WIDE
- Adjusted and fixed all margins and padding to have consistent gutters across site. 
- All Page Headers are now to be the same height as the 'Trope Collaborative' header
- Go Button and Header both given matching hardcoded top padding and alignment (check in full screen view)

HEADERS
- Header title and page title given same size. 
- All pages has top hr removed. All headers given hr after the site tagline. 
- All unified. Home page has it's own menu, every other page has been given access to the secondary level menu. There is no tertiary-specific menu. This keeps it simple: all sub level pages and the home page are available from any non-home page. 

SECONDARY PAGES
- All have new margins and headers - 140/170px page gutters depending on element
- All adjusted to the layout changes on the home page

INTEREST AREAS
- Left margin is removed when under a certain ViewPort px width in order to keep content viewable. Expands into the full width when over 1200px.

INTERVIEWS
- Design updated to other pages. Will also scale content margins with screen size! 

TERTIARY PAGE:
- All have new margins and headers - 140/170px page gutters depending on element
- All adjusted to the layout changes on the home page
- I am now building these, despite the delay. 

PROCESS IMG UNDER ACTIVATING
- Fixed pending review, as we saw it on Tue night.

FEEDING THE LION
- Adapted page type off the old site, will def need some feedback on the typography heirarchy.

ALL THE POSSIBLE PAGE TYPES ARE PRESENT, WITH CORRECT PAGE MARGINS and TOP HEADER
- I can now create all the tertiary pages, this process will be fast (3ish days).

**Comment by akallish** [comment]
08-04 Comments

Hello @Tombodil . I reviewed the latest iteration of the different site sections and we are making progress. I have the following comments :

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Default Home Page

• Go and dropdown
- Not aligned with Trope Collaborative
- back to sticking again

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Default Experience

• Go and dropdown
- should experience show up when you are in experience? True for all home page carousel choices

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Default Solving

Solving through capabilities
• the four titles are too close to the rule

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Instagram

• Change to "A wide variety of moments"

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Interest Areas

• Change to "Key trends and methods that inform our practice"

**Comment by Tombodil** [comment]
### THUR FIXES

Go And Dropdown
- Text given same size as trope header and baselines of the fonts were aligned
- First HR under trope pulled up 3 px to match menu bottom border. 
- Dropdown menu adjusted to match
- Open/Close behavior adjusted and confirmed. If this is still wierd for you, I have another way of remaking the logic. 

Default Experience

- Should experience show up when you are in experience? Yes: It's disorienting to have your current option missing in the nav. The primary reasons a user would want to see the menu are; making a different choice or checking what section they are on. Somewhat limited benefit as the menu generally stays closed. 

Instagram

- Changed to "A wide variety of moments."

Interest Areas

- Changed to "Key trends and methods that inform our practice."

ALL PAGE HEADERS
- based on the above, all page headers are now first-letter capitalized, period at end. Some of the other titles were sentice capitalized, hence my take. This can be changed to preference. 

Solving through capabilities
- the four titles have been given 7px additional internal top padding

**Comment by Tombodil** [comment]
FRI EXPANSIONS

- All publishing pages built structurally

**Comment by akallish** [comment]
@Tombodil i will look at the site today and comment
