### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by akallish** [Tombodil/Trope22#8]
Hey @Tombodil how are you? How is the build coming? Did you look at the revised home page pdf?

**Comment by Tombodil** [comment]
Hey Adam.

Wanted to get back to you, last week was relentless.

Dad needed some help due to recent complications, I had to send over photos
to the magazine three times due to focus settings (they were cool about it
but still embarassing) and I knew we needed velocity on this migration. I
rushed through two painting commissions to clear my schedule.

Also had a medication change up so had a day or two of being tired.

The communication gap is 100% my fault while the events just dropped in my
lap. Apologies for any concern this caused. My life has been 1000mph as of
late.

Even as this is 'not an emergency,' I don't want to let this get too
behind. I originally said a month after the main page designs, we should be
reviewing details before launch.

That gives me three weeks and currently that seems a good timetable.
Specially now that I'm back to one thing at a time.

-------------------

Now, yes.
I saw the revised pdf and it looks good. Nested carousels like the IBM
site, different design. The section transition is triggered by a sub menu
on the left aligned slug.

I'm back to adapting pages into the site structure and no issues so far. I
will build the home page this coming tue-wed and will be filling out the
pages throughout the week. I'll be adding the home page sections as they
are provided.

I'd like to schedule a meeting for next thur or Friday to review where we
are, the project timetable and any changes or info needed. This gives me a
few days to get the other page types up to review level and build what I
have on the home page.

If either of those nights work (9, 10th), 9pm, let me know and I can
schedule the meeting.

**Comment by akallish** [comment]
Hey Tom

First, family comes first. So slow down when it comes to my request. It is not an emergency.

Keep me informed when your life is less hectic. Good luck with your father.


- - - - - - - - - - - 
Sent in motion and at the mercy of auto spell 😈
- - - - - - - - - - - 
Blog : http://bit.ly/2YMwwt7
- - - - - - - - - - -

**Comment by Tombodil** [comment]
old issue, closed
